PUT https://q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items HTTP/1.1
Content-Type: application/json

{"id": "123", "price": 123, "name": "myitem", "description": "mydescription"}

###
GET q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items HTTP/1.1

###
GET q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items/123 HTTP/1.1

###
DELETE q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items/123 HTTP/1.1

###
GET https://iz6b0as539.execute-api.us-west-2.amazonaws.com/emailHeaders HTTP/1.1
Content-Type: application/json

{
    "num": 5
}