PUT https://q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items HTTP/1.1
Content-Type: application/json

{"id": "123", "price": 123, "name": "myitem", "description": "mydescription"}

###
GET q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items HTTP/1.1

###
GET q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items/123 HTTP/1.1

###
DELETE q5wo67s5l8.execute-api.us-west-1.amazonaws.com/items/123 HTTP/1.1

###
GET https://iz6b0as539.execute-api.us-west-2.amazonaws.com/emailHeaders HTTP/1.1
Content-Type: application/json

{
    "num": 5
}

###
GET https://iz6b0as539.execute-api.us-west-2.amazonaws.com/emailSummary HTTP/1.1
Content-Type: application/json

{
    "email": {
        "id": "1826f0f28d5ef592",
        "threadID": "1826f0f28d5ef592",
        "from": "Elianne Van Slyke <ellievanslyke@gmail.com>",
        "to": "Patti Segulja-Lau <Patti@pacific-apartments.com>, Bob Taylor <Bob@pacific-apartments.com>",
        "date": "Fri, 5 Aug 2022 11:30:00 -0600",
        "subject": "Rent Moola/LetUs Next Steps",
        "snippet": "Hi everyone - We are still having trouble connecting with LetUs/Rent Moola support to make a building-wide change. Tenants who have reached out to them directly have had success with inputting their",
        "labels": [
        "UNREAD",
        "IMPORTANT",
        "CATEGORY_PERSONAL",
        "INBOX"
        ]
    }
    
}